// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data.Contexts;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(ObjectAnnotationToolDbContext))]
    [Migration("20221104200146_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebAPI.Models.Annotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("ObjectClassId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjectClassId");

                    b.ToTable("Annotations");
                });

            modelBuilder.Entity("WebAPI.Models.ObjectClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ObjectClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sebze"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Meyve"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("ObjectClassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjectClassId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nohut",
                            ObjectClassId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fasulye",
                            ObjectClassId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Elma",
                            ObjectClassId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Armut",
                            ObjectClassId = 2
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Annotation", b =>
                {
                    b.HasOne("WebAPI.Models.ObjectClass", "ObjectClass")
                        .WithMany()
                        .HasForeignKey("ObjectClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectClass");
                });

            modelBuilder.Entity("WebAPI.Models.Tag", b =>
                {
                    b.HasOne("WebAPI.Models.ObjectClass", "ObjectClass")
                        .WithMany("Tags")
                        .HasForeignKey("ObjectClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectClass");
                });

            modelBuilder.Entity("WebAPI.Models.ObjectClass", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
